---
title: "My experience"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

## Personal information

Tel: (+1) 5307461242 | Email: yz4436@cumc.columbia.edu

## Education experience

University of California, Davis
B.S. in Applied Mathematics
* GPA: 3.579/4.0
Sept. 2018 – Mar. 2022
Relevant Coursework: Real Analysis, Numerical Analysis, Stochastic Process, Linear Algebra, Discrete Mathematics, Discrete Mathematics for CS, Development in Unix & C/C++, Probability, Intro to Data Structures, Calculus, Intro to Programming, Classical Physics, Vector Analysis, Combinatorics, Ordinary Diff Equations,
Modern Algebra
* Awards: Dean’s Honors List (Spring 2021)

## Professional experience

#### Hangzhou Kenwo Automation Control Co., LTD
Software Engineering Intern - License Plate Detection & Recognition July 2021 - Sept. 2021

* Collected 50k automobile images from open-source datasets and camera capturing

* Removed corrupted images by checking pixel value at specific positions using OpenCV and Python

* Performed data augmentation by rotating, resizing, adding white noise and alternating brightness, contrast, transparency using OpenCV and Python

* Utilized pre-trained YOLOv5 for fine-tuning the image data and performed the object detection of license plates

* Used pre-trained EfficientNet to build a classifier on the license plates images and recognized the car license number within the images

* Built data pipeline in Apache Spark to automate the data cleaning and preprocessing

#### Jiangsu Runyang, Inc 
Software Engineering Intern - IoT Time Series Prediction Mar. 2021 - June 2021

* Collected real-time machinery and equipment data such as operational status, speed, direction, power, voltage, energy usage and stored them in Ali Cloud Object Storage Service

* Preprocessed the time series of electric current and operational status by interpolating missing values, removing corrupted points and standardizing time format using Python Pandas

* Computed Hurst Exponent to verify the long-term memory of the time series

* Fitted ARMA model using statsmodels in Python and predicted the possibility of malfunctions in different types of machines based on the electric current time series

* Fitted ARIMA model using statsmodels in Python to predict the temperature of various machinery components and created alerts when there is an expected overheat

* Performed model hyper-parameter tuning by cross-validation using scikit-learn in Python

#### Xuzhou Construction Machinery Group Co., Ltd (XCMG) 
Software Engineering Intern - Data Engineering Dec. 2020 - Feb. 2021

* Wrote web scrapers and Weibo bots to track the keywords mentioned with the top 20 heavy machinery manufacturing companies in China using Scrapy and Weibo Python API

* Converted the keywords to vectors using GloVe and visualized the vectors by PCA using Matplotlib

* Performed clustering on the word vectors using KMeans in Python scikit-learn

* Analyzed the different results from a diverse number of clusters and generated word cloud visualization using WordCloud in Python






