---
title: "NY Noaa dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```


```{r}
data("ny_noaa")
ny_noaa = 
  ny_noaa %>%
  filter(id %in% c("USC00300023","USC00300028", "USC00300055", "USC00300063", 
                   "USC00300093", "USC00300085", "USC00300183", "USC00300220")) %>% 
  drop_na()
```

Column {data-width=650}
-----------------------------------------------------------------------

### Snowfall in mm of data from 8 weather stations

```{r}
ny_noaa %>%
  mutate(text_label = str_c("Snowfall in mm is", snow)) %>% 
  plot_ly(
    x = ~date, y = ~snow, type = "scatter", mode = "markers",
    color = ~id, text = ~text_label, alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Minimum temperature (tenths of degrees C) for 8 weather stations

```{r}
ny_noaa %>% 
  plot_ly(x = ~id, y = ~tmin, color = ~id, type = "box", colors = "viridis")
```

### Number of effective data rows by 8 weather stations

```{r}
ny_noaa %>%
  count(id) %>% 
  mutate(id = fct_reorder(id, n)) %>%
  plot_ly(x = ~id, y = ~n, color = ~id, type = "bar", colors = "viridis")
```

